### ISSUE TITLE
Projeto parecido

### ISSUE THREAD

**Issue by guilhermecgs** [amgsnt/portal-cei#1]
bem parecido hein:-)

https://github.com/guilhermecgs/ir/blob/master/src/crawler_cei.py

**Comment by amgsnt** [comment]
> bem parecido hein:-)
> 
> 
> 
> https://github.com/guilhermecgs/ir/blob/master/src/crawler_cei.py

Nossa que legal :)
A mesma ideia

**Comment by amgsnt** [comment]
> bem parecido hein:-)
> 
> https://github.com/guilhermecgs/ir/blob/master/src/crawler_cei.py

Que legal :)
A mesma ideia
